---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: ztp
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tftpboot-data
  namespace: ztp
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
